name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # --- ADD THIS PERMISSIONS BLOCK ---
    permissions: 
      contents: write # This grants permission to commit and push files
    # ----------------------------------
    steps:
      - uses: actions/checkout@v4
      - uses: platane/snk@v3
        with:
          github_user_name: azmainofficial
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸŽ¨ Feat: Generate latest contribution snake"
          file_pattern: output/github-contribution-grid-snake.svg
